name: backend

on:
  workflow_call:

defaults:
  run:
    working-directory: ./backend

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK 8
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '8.0.442'
          distribution: 'zulu'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.3.0
      - name: Execute Gradle 'check' task
        run: ./gradlew check --continue --no-daemon --no-watch-fs
      - name: Set up Docker CLI
        uses: docker/setup-buildx-action@v3.9.0
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.13.0
        with:
          context: "{{defaultContext}}:backend"
          cache-from: type=gha
          cache-to: type=gha,mode=max
