name: ping-render

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Spin up Render instance
        run: |
          curl -H 'Content-Type: application/json' -d '{login: "", password: ""}' https://message-board-nnel.onrender.com/register
