name: ping-render

on:
  workflow_dispatch:
  schedule:
    - cron: "*/16 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Spin up Render instance
        run: curl https://message-board-nnel.onrender.com/swagger-ui/index.html